### ISSUE TITLE
Pin to style version

### ISSUE THREAD

**Issue by 1ec5** [incanus/ViewAnnotationDemo#1]
This demo [uses](https://github.com/incanus/ViewAnnotationDemo/blob/db7d93b37a8e5cb8f3bfd449d40667de9ac52fd1/ViewAnnotationDemo/ViewController.swift#L19) the `MGLStyleDefaultVersion` constant. The documentation for that constant comes with all the usual caveats about essentially pinning to master. Although this demo doesn’t make use of any details in the Dark style that would break between style releases, we probably shouldn’t be encouraging developers to use this constant for any purpose other than knowing what MGLMapView, MGLTilePyramidOfflineRegion, or MGLStyle defaults to. See https://github.com/mapbox/mapbox-gl-native/pull/4759#discussion_r60455953 for further discussion about this constant.

/cc @incanus @friedbunny

**Comment by incanus** [comment]
👉 https://github.com/mapbox/ViewAnnotationDemoiOS

**Comment by 1ec5** [comment]
The saga continues in mapbox/ViewAnnotationDemoiOS#1.

**Comment by incanus** [comment]
💣
